booking/urls.py
from django.urls import path, re_path

from . import views


app_name = 'booking'

urlpatterns = [
    path('select_child', views.SelectChild.as_view(), name='select_child'),
    re_path(r'^calendar/(?P<child_id>\d+)/$', views.Calendar.as_view(),
            name='calendar'),
    path('modify', views.Modify.as_view(), name='modify'),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('legal_notice', views.LegalNotice.as_view(), name='legal_notice'),
]

registration/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LegalGuardianForm


app_name = 'registration'

urlpatterns = [
    path(
        'login',
        auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='registration/logout.html'
        ),
        name='logout'
    ),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('regfamily', views.RegFamily.as_view(), name='regfamily'),
    path('myaccount', views.ManageAccount.as_view(), name='myaccount'),
    re_path(
        r'^regchild_step1\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(),
        name='regchild_step1'
    ),
    re_path(
        r'^regchild_step2\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(
            form_class=LegalGuardianForm,
            session_key='lg1',
            title='Mère / Responsable Légal 1',
            step=2
        ),
        name='regchild_step2'
    ),
    re_path(
        r'^regchild_step3\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(
            form_class=LegalGuardianForm,
            session_key='lg2',
            title='Père / Responsable Légal 2',
            step=3
        ),
        name='regchild_step3'
    ),
    re_path(
        r'^regchild_step4\/?(?P<child_id>\d+)?\/?',
        views.RegChildFinal.as_view(),
        name='regchild_step4'),
    path('regperson', views.RegPerson.as_view(), name='regperson'),
    path('modfamily', views.RegFamily.as_view(
        modify=True
    ), name='modfamily'),
    path('delete_this', views.DeleteThis.as_view(), name='delete_this'),
]

home/models.py
from django.db import models


class Price(models.Model):
    """ Prices for day or half-day in terms of family quotient """

    family_quotient = models.CharField(max_length=15,
                                       verbose_name='Quotient familial')
    day = models.DecimalField(max_digits=4, decimal_places=2,
                              verbose_name='Prix journée')
    half_day = models.DecimalField(max_digits=4, decimal_places=2,
                                   verbose_name='Prix demi-journée')

    class Meta:
        ordering = ['day']
        verbose_name = 'Tarif'
        constraints = [
            models.UniqueConstraint(fields=['family_quotient'],
                                    name='unique_quotient'),
        ]

    def __str__(self):
        return 'Quotient familial {}'.format(self.family_quotient)

home/views.py
from django.shortcuts import render
from django.views import View
from .models import Price

from booking.models import Activity


class Index(View):
    """ A view to display general information """

    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        prices = Price.objects.all()
        agenda = Activity.make_agenda()

        context = {
            'prices': prices,
            'agenda': agenda
        }
        return render(request, self.template_name, context)


class LegalNotice(View):
    """ A view to display legal notice """

    template_name = 'home/legalnotice.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

home/templates/home/agenda.html
<div class="inner-section">
  <h3>Choisissez une catégorie.</h3>
  {% for category in agenda %}
  <div class="categories">
    <p class="text-small">{{ category.description }}</p>
    <button class="form-button" type="button" name="button" onclick="toggleAgenda(this)">{{ category.name }}</button>
  </div>
  {% endfor %}
  {% for category, days in agenda.items %}
    <div class="{{ category.name }} container hidden">
      <h3>{{ category.name }}</h3>
      <div class="card-box">
      {% for day, activities in days.items %}
        <div class="card">
          <h4>{{ day }}</h4>
          {% for activity in activities %}
          <div class="inner-card">
            <p class="text-small">{{ activity.start_time }}</p>
            <p class="card-center">{{ activity.name }}</p>
            <p class="text-small">{{ activity.end_time }}</p>
          </div>
          {% endfor %}
        </div>
      {% endfor %}
      </div>
    </div>

  {% endfor %}
</div>

home/templates/home/base.html
<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Hazel</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://kit.fontawesome.com/575962c641.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    {% load static %}
    <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="{% static 'home/img/favicon.png' %}" />
  </head>
  <body>
    <header id="home-header">
      <nav class="topnav" id="myTopnav">
        <a id="logo" href="{% url 'home:index' %}">ALSH Monflanquin</a>
        <a href="/#info">Info</a>
        <a href="/#agenda">Agenda</a>
        <a href="/#registration">Inscription</a>
        <a href="{% url 'booking:select_child' %}">Réservation</a>
        <a href="/#contact">Contact</a>
        {% if user.is_authenticated %}
        <div class="dropdown">
          <button id="dropdown-button" onclick="dropDown()" class="dropbtn">
            <i class="far fa-user-circle fa-3x"></i>
            <span>{{ user.username }}</span>
          </button>
          <div id="account" class="dropdown-content">
            <a href="{% url 'registration:myaccount' %}">Mon compte</a>
            <a href="{% url 'registration:logout' %}">Déconnexion</a>
          </div>
        </div>
        {% else %}
        <div class="dropdown">
          <button id="dropdown-button" onclick="dropDown()" class="dropbtn">
            <i class="far fa-user-circle fa-3x"></i>
            <span>Connexion</span>
          </button>
          <div id="account" class="dropdown-content">
            <a href="{% url 'registration:login' %}">Se connecter</a>
            <a id="create-account" href="{% url 'registration:signup' %}">Créer un compte</a>
          </div>
        </div>

        {% endif %}
        <a href="javascript:void(0);" class="h-icon" onclick="responsiveMenu()"><i class="fas fa-bars fa-2x"></i></a>
      </nav>
      <p id="booking-msg" class="hidden">test test test test test test</p>
    </header>
    {% block content %}{% endblock %}
    <footer>
      <a href="{% url 'home:legal_notice' %}">Mentions légales</a>
      <span> | </span>
      <a href="/#contact">Contact</a>
      <p>L'application et le site ont été créés par Germain GAILLARD.</p>
      <a href="mailto:gaillard.germain@gmail.com"><i class="far fa-envelope"></i></a>
      <a href="https://github.com/screw-pack" target="_blank" rel="noopener noreferrer"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/gaillard-germain-2301861b4/" target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin-in"></i></a>
    </footer>
  </body>
  <script src="{% static 'home/js/scripts.js' %}"></script>
</html>

home/templates/home/contact.html
<div class="inner-section">
  <h3>ALSH Monflanquin</h3>
  <p>Lieu-dit Coulon – 47150 MONFLANQUIN</p>
  <p><i class="fas fa-phone-square"></i> 05.53.36.41.38</p>
  <p><i class="fas fa-envelope-square"></i> alsh.monflanquin@orange.fr</p>
</div>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
  {% block content %}
  <div class="intro" style="background-image: url({% static 'home/img/home_intro.jpg' %})">
    <h1 class="main-title">Accueil de loisirs de Monflanquin</h1>
  </div>
  <section id="info">
    <div class="s-icon">
      <i class="fas fa-info fa-2x"></i>
    </div>
    <h1 class="section-title">Informations</h1>
    <hr class="separator">
    {% include 'home/info.html' %}
  </section>
  <section id="agenda">
    <div class="s-icon">
      <i class="far fa-calendar-alt fa-2x"></i>
    </div>
    <h1 class="section-title">Agenda</h1>
    <hr class="separator">
    {% include 'home/agenda.html' %}
  </section>
  <section id="registration">
    <div class="s-icon">
      <i class="fas fa-file-alt fa-2x"></i>
    </div>
    <h1 class="section-title">Inscription</h1>
    <hr class="separator">
    {% include 'home/registration.html' %}
  </section>
  <section id="contact">
    <div class="s-icon">
      <i class="fas fa-phone fa-2x"></i>
    </div>
    <h1 class="section-title">Nous contacter</h1>
    <hr class="separator">
    {% include 'home/contact.html' %}
  </section>
  {% endblock %}

home/templates/home/info.html
<div class="inner-section">
  <h2>Horaires d'ouverture</h2>
  <p>L'Accueil de Loisirs est ouvert durant les vacances scolaires et les mercredis.</p>
  <p>Les horaires de fonctionement sont de <strong>7h30</strong> à <strong>18h30</strong>.</p>
  <p>Dans le prix journée est compris une collation le matin, le repas de midi et un goûter l'aprés-midi.</p>
  <h2>Tarifs</h2>
  <table id="prices">
    <tr>
      <th>Quotient Familial</th>
      <th>Prix journée</th>
      <th>Prix demi-journée</th>
    </tr>
    {% for price in prices %}
      <tr>
        <td>{{ price.family_quotient }}</td>
        <td>{{ price.day }}€</td>
        <td>{{ price.half_day }}€</td>
      </tr>
    {% endfor %}
  </table>
  <p class="text-warning">
    Les factures doivent être <strong>obligatoirement</strong> payées avant le 20 du mois suivant.
  </p>
  <p>
    Le réglement se fait <strong>directement</strong> au trésor public de Monflanquin.
  </p>
  <p>
    N'oubliez pas vos <span class="text-warning">justificatif CAF ou MSA (avec votre QF) de l'année en cours</span>
    afin que nous puissions vous appliquer le tarif correspondant,
    <span class="text-warning text-small">sinon le tarif maximum sera appliqué.</span>
  </p>
</div>

home/templates/home/legalnotice.html
{% extends 'home/base.html' %}

{% block content %}

  <section class="top-offset notice">
    <h1>MENTIONS LEGALES</h1>
    <hr class="separator">
    <h2>Identité</h2>
    <p>Nom du site web : hazel</p>
    <p>Adresse : 128.199.53.172</p>
    <p>Propriétaire : Germain GAILLARD</p>
    <p>Responsable de publication : Germain GAILLARD</p>
    <p>Conception et réalisation : Germain GAILLARD</p>
    <p>Hébergement : <a href="https://www.digitalocean.com/">DigitalOcean</a></p>
    <h2>Conditions d’utilisation</h2>
    <p>
      L’utilisation du présent site implique l’acceptation pleine et entière
      des conditions générales d’utilisation décrites ci-après.
      Ces conditions d’utilisation sont susceptibles d’être modifiées ou
      complétées à tout moment.
    </p>
    <h2>Informations</h2>
    <p>
      Les informations et documents du site sont présentés à titre indicatif,
      n’ont pas de caractère exhaustif, et ne peuvent engager la responsabilité
      du propriétaire du site.
    </p>
    <p>
      Les informations sont fournies par <a href="/#contact">l'ALSH de Monflanquin</a>.
    </p>
    <p>
      Le propriétaire du site ne peut être tenu responsable des dommages
      directs et indirects consécutifs à l’accès au site.
    </p>
    <h2>Propriété intellectuelle</h2>
    <p>
      Sauf mention contraire, tous les éléments accessibles sur le site
      (textes, images, graphismes, logo, icônes, sons, logiciels, etc.)
      restent la propriété exclusive de leurs auteurs, en ce qui concerne
      les droits de propriété intellectuelle ou les droits d’usage.<a class="text-small text-warning" href="#1">1</a>
    </p>
    <p>
      Toute reproduction, représentation, modification, publication, adaptation
      de tout ou partie des éléments du site, quel que soit le moyen
      ou le procédé utilisé, est interdite, sauf autorisation écrite préalable
      de l’auteur.<a class="text-small text-warning" href="#2">2</a><a class="text-small text-warning" href="#3">3</a>
    </p>
    <p>
      Toute exploitation non autorisée du site ou de l’un quelconque des
      éléments qu’il contient est considérée comme constitutive
      d’une contrefaçon et poursuivie.<a class="text-small text-warning" href="#4">4</a>
    </p>
    <p>
      Les marques et logos reproduits sur le site sont déposés par les sociétés
      qui en sont propriétaires.
    </p>
    <h2>Liens</h2>
    <h3>Liens sortants</h3>
    <p>
      Le propriétaire du site décline toute responsabilité et n’est pas engagé
      par le référencement via des liens hypertextes, de ressources tierces
      présentes sur le réseau Internet, tant en ce qui concerne leur contenu
      que leur pertinence.
    </p>
    <h3>Liens entrants</h3>
    <p>
      Le propriétaire du site autorise les liens hypertextes vers l’une des
      pages de ce site, à condition que ceux-ci ouvrent une nouvelle fenêtre
      et soient présentés de manière non équivoque afin d’éviter :
    </p>
    <ul>
      <li>tout risque de confusion entre le site citant et le propriétaire du site</li>
      <li>ainsi que toute présentation tendancieuse, ou contraire aux lois en vigueur</li>
    </ul>
    <p>
      Le propriétaire du site se réserve le droit de demander la suppression
      d’un lien s’il estime que le site source ne respecte pas les règles ainsi définies.
    </p>
    <h2>Confidentialité</h2>
    <p>
      Tout utilisateur dispose d’un droit d’accès, de rectification et
      d’opposition aux données personnelles le concernant, en effectuant
      sa demande écrite et signée, accompagnée d’une preuve d’identité.
      <a class="text-small text-warning" href="#5">5</a><a class="text-small text-warning" href="#6">6</a><a class="text-small text-warning" href="#7">7</a><a class="text-small text-warning" href="#8">8</a>
    </p>
    <p>
      Le site ne recueille pas d’informations personnelles,
      et n’est pas assujetti à déclaration à la CNIL.<a class="text-small text-warning" href="#9">9</a>
    </p>
    <h2>Crédits</h2>
    <p>Photos de fond : <a href="#"></a></p>
    <p>Autres photos : <a href="#"></a></p>
    <p>Informations : <a href="/#contact">ALSH de Monflanquin</a></p>
    <p>Icones : <a href="https://fontawesome.com/">https://fontawesome.com/</a></p>
    <p>Hébergement : <a href="https://www.digitalocean.com/">DigitalOcean</a></p>
    <p>Merci à : <a href="https://openclassrooms.com/">OpenClassRooms</a></p>
    <hr/>
    <p><a href="https://www.webexpress.fr/">Mentions légales fournies par WebExpress – Version 1.5</a>
       – Utilisation libre sous <a href="http://creativecommons.org/licenses/by-nc-nd/3.0/fr/">Licence Creative Commons CC BY-NC-ND 3.0 FR / creativecommons.org</a></p>
  </section>
  <section class="notice">
    <ol>
      <li id="1">Articles L111-1 et suivants du Code de la Propriété Intellectuelle du 1er juillet 1992</li>
      <li id="2">Article 41 de la loi du 11 mars 1957</li>
      <li id="3">Article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995</li>
      <li id="4">Articles L.335-2 et suivants du Code de Propriété Intellectuelle</li>
      <li id="5">Loi n° 78-87 du 6 janvier 1978, modifiée par la loi n° 2004-801 du 6 août 2004, relative à l’informatique, aux fichiers et aux libertés</li>
      <li id="6">Articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés</li>
      <li id="7">Loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données</li>
      <li id="8">Loi n° 2004-801 du 6 août 2004</li>
      <li id="9">Article 6 de la <a href="https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000801164&dateTexte=20160619">loi n° 2004-575 du 21 juin 2004</a> pour la confiance dans l’économie numérique</li>
    </ol>
  </section>

{% endblock %}

home/templates/home/registration.html
<div class="inner-section">
  <h3>Vous pouvez Inscrire votre enfant directement sur le site:</h3>
  <p>
    Pour cela vous devez <a class="inline" href="{% url 'registration:login' %}">vous connecter</a>, ou
    <a class="inline" href="{% url 'registration:signup' %}">créer un compte</a>
    dans la rubrique connexion --> créez un compte.
  </p>
  <p>
    Puis inscrire un enfant dans la rubrique: Mon compte --> Ajouter un enfant.
  </p>
  <p>
    Enfin pour réserver les journées au centre pour les enfants inscris, cliquez sur la rubrique
    <a href="{% url 'booking:select_child' %}">Réservation</a>
    dans la barre de navigation
  </p>
  <h3>Vous pouvez également l'inscrire par voie traditionnelle:</h3>
  <p>
    En <a href="/#contact">nous</a>
    retournant la fiche d'inscription et la fiche de réservation, disponibles ci-dessous, dûment remplie.
  </p>
  <p class="text-warning">
    Nous insistons sur l'importance de ces fiches car sans leur retour nous nous réservons le droit de refuser l'accés de vos enfants à l'ALSH.
  </p>
  <h3>Documents imprimables</h3>
  <ul class="not-dotted">
    {% load static %}
    <li>
      <a href="{% static 'home/files/rules.pdf' %}" target="_blank" rel="noopener noreferrer">
        Réglement intérieur
      </a>
    </li>
    <li>
      <a href="{% static 'home/files/registration_form.pdf' %}" target="_blank" rel="noopener noreferrer">
        Fiche d’inscription ALSH/ALP
      </a>
    </li>
    <li>
      <a href="{% static 'home/files/child_registration_2021.pdf' %}" target="_blank" rel="noopener noreferrer">
        Fiche inscription été 2021
      </a>
    </li>
    <li>
      <a href="{% static 'home/files/medical_form.pdf' %}" target="_blank" rel="noopener noreferrer">
        Fiche sanitaire de liaison
      </a>
    </li>
  </ul>
  <h3 class="text-warning">L'inscription aux sorties se fait directement au centre et non sur la fiche de réservation.</h3>
</div>