booking/urls.py
from django.urls import path, re_path

from . import views


app_name = 'booking'

urlpatterns = [
    path('select_child', views.SelectChild.as_view(), name='select_child'),
    re_path(r'^calendar/(?P<child_id>\d+)/$', views.Calendar.as_view(),
            name='calendar'),
    path('modify', views.Modify.as_view(), name='modify'),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('legal_notice', views.LegalNotice.as_view(), name='legal_notice'),
]

registration/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LegalGuardianForm


app_name = 'registration'

urlpatterns = [
    path(
        'login',
        auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='registration/logout.html'
        ),
        name='logout'
    ),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('regfamily', views.RegFamily.as_view(), name='regfamily'),
    path('myaccount', views.ManageAccount.as_view(), name='myaccount'),
    re_path(
        r'^regchild_step1\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(),
        name='regchild_step1'
    ),
    re_path(
        r'^regchild_step2\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(
            form_class=LegalGuardianForm,
            session_key='lg1',
            title='Mère / Responsable Légal 1',
            step=2
        ),
        name='regchild_step2'
    ),
    re_path(
        r'^regchild_step3\/?(?P<child_id>\d+)?\/?',
        views.RegChild.as_view(
            form_class=LegalGuardianForm,
            session_key='lg2',
            title='Père / Responsable Légal 2',
            step=3
        ),
        name='regchild_step3'
    ),
    re_path(
        r'^regchild_step4\/?(?P<child_id>\d+)?\/?',
        views.RegChildFinal.as_view(),
        name='regchild_step4'),
    path('regperson', views.RegPerson.as_view(), name='regperson'),
    path('modfamily', views.RegFamily.as_view(
        modify=True
    ), name='modfamily'),
    path('delete_this', views.DeleteThis.as_view(), name='delete_this'),
]

booking/models.py
from django.db import models
from django.template.defaultfilters import date as _date
from datetime import date, timedelta

from registration.models import Child, Category


class Period(models.Model):
    """ Holidays periods """

    name = models.CharField(max_length=50, verbose_name='Nom')
    start_date = models.DateField(verbose_name='Date début')
    end_date = models.DateField(verbose_name='Date fin')

    class Meta:
        verbose_name = "Période d'ouverture"
        verbose_name_plural = "Périodes d'ouverture"
        constraints = [
            models.UniqueConstraint(fields=['name'],
                                    name='unique_period'),
        ]

    def __str__(self):
        return self.name

    def get_days(self, weekday):
        """ return a list of all given weekday in the period
            (0=monday...6=sunday)"""
        all_days = []
        current = self.start_date + timedelta(days=1)
        while current != self.end_date:
            if current.weekday() == weekday:
                all_days.append(current)
            current += timedelta(days=1)
        return all_days

    def make_calendar(self, child, wednesday=[]):
        """ Returns a dict {month: {weekday: [date]}} of the period"""

        calendar = {}
        current = self.start_date + timedelta(days=1)

        if self.name == 'Périscolaire':
            excluded = [0, 1, 3, 4, 5, 6]
        else:
            excluded = [5, 6]

        while self.end_date != current:

            month = _date(current, 'F Y')
            weekday = _date(current, 'D')

            if (current.weekday() not in excluded and
                    current > date.today() and current not in wednesday):
                if month not in calendar:
                    calendar[month] = {}

                if weekday not in calendar[month]:
                    calendar[month][weekday] = {}

                try:
                    slot = Slot.objects.get(day=current)

                    try:
                        booking = Booking.objects.get(slot=slot, child=child)
                        calendar[month][weekday][current] = booking

                    except Booking.DoesNotExist:
                        if slot.is_full:
                            calendar[month][weekday][current] = 'full'
                        else:
                            calendar[month][weekday][current] = None

                except Slot.DoesNotExist:
                    calendar[month][weekday][current] = None

            current += timedelta(days=1)

        return calendar


class Slot(models.Model):
    """ Slot for booking (the only interest is to store is_full field)"""

    day = models.DateField(verbose_name='Date')
    is_full = models.BooleanField(default=False, verbose_name='Complet')

    class Meta:
        ordering = ['day']
        verbose_name = 'Jour'
        constraints = [
            models.UniqueConstraint(fields=['day'],
                                    name='unique_slot'),
        ]

    def __str__(self):
        return _date(self.day, 'd F Y')

    def update_slot(self):
        """ Updates slot state when user booked a day """
        booking_count = Booking.objects.filter(slot=self).count()
        activity_count = Activity.objects.filter(slot=self).count()

        if booking_count == 0 and activity_count == 0:
            self.delete()
        elif booking_count >= 60 and not self.is_full:
            self.is_full = True
            self.save()
        elif booking_count < 60 and self.is_full:
            self.is_full = False
            self.save()


class Booking(models.Model):
    """ Booking book """

    child = models.ForeignKey(Child, related_name='booking',
                              on_delete=models.CASCADE, verbose_name='Enfant')
    slot = models.ForeignKey(Slot, related_name='booking',
                             on_delete=models.CASCADE, verbose_name='Créneau')
    whole = models.BooleanField(default=True, verbose_name='Journée complète')
    validated = models.BooleanField(default=False, verbose_name='Validé')

    class Meta:
        verbose_name = 'Réservation'
        constraints = [
            models.UniqueConstraint(fields=['child', 'slot'],
                                    name='unique_booking'),
        ]

    def __str__(self):
        return '{} {}'.format(self.child, self.slot)

    def update_booking(self, command):
        """ updates booking when user cancelled or booked a day """

        if command == 'cancel':
            self.delete()

        elif command == 'full-day' and not self.whole:
            self.whole = True
            self.save()

        elif command == 'half-day' and self.whole:
            self.whole = False
            self.save()


class Activity(models.Model):
    """ Planned activities to entertain children """

    name = models.CharField(max_length=100, verbose_name='Nom')
    categories = models.ManyToManyField(Category, related_name='activities',
                                        verbose_name='Catégorie')
    slot = models.ForeignKey(Slot, related_name='activities',
                             on_delete=models.CASCADE, verbose_name='Date',
                             null=True)
    start_time = models.TimeField(verbose_name='Heure début')
    end_time = models.TimeField(verbose_name='Heure fin')
    extra_charge = models.DecimalField(max_digits=4, decimal_places=2,
                                       verbose_name='Supplément tarif',
                                       blank=True, null=True)

    class Meta:
        ordering = ['start_time']
        verbose_name = 'Activité'

    def __str__(self):
        return self.name

    @classmethod
    def make_agenda(cls):
        all_categories = Category.objects.all()
        slots = Slot.objects.filter(day__gte=date.today())
        agenda = {}

        for category in all_categories:
            agenda[category] = {}
            for slot in slots:
                new_day = _date(slot.day, 'D d F')
                activities = cls.objects.filter(slot=slot.id)
                activities = activities.filter(categories=category)
                if activities:
                    agenda[category][new_day] = activities

        return agenda

booking/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from django.http import Http404
from datetime import date
from registration.models import Family, Child
from .models import Period, Booking, Slot


class SelectChild(View):
    """ A view to select child for booking """

    template_name = 'booking/select_child.html'

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated:
            try:
                family = Family.objects.get(user=request.user.id)

            except Family.DoesNotExist:
                return redirect('registration:regfamily')

            children = Child.objects.filter(family=family)

            if not children.count():
                return redirect('registration:regchild_step1')

            context = {'children': children}

            return render(request, self.template_name, context)

        else:
            return redirect('registration:login')


class Modify(View):
    """ A view triggered by Ajax to manage booking actions """

    def post(self, request, *args, **kwargs):

        response = {}

        child_id = request.POST.get('child_id')
        command = request.POST.get('command')
        day = request.POST.get('day')

        child = Child.objects.get(id=child_id)

        slot, created = Slot.objects.get_or_create(
            day=date.fromisoformat(day)
        )
        booking, created = Booking.objects.get_or_create(
            child=child,
            slot=slot
        )

        booking.update_booking(command)
        slot.update_slot()

        if command == 'cancel':
            msg = 'La réservation du {} pour {} a été annulée.'.format(
                slot, child.firstname
            )
        else:
            msg = 'La réservation du {} pour {} a été enregistrée.'.format(
                slot, child.firstname
            )
        response['msg'] = msg
        return JsonResponse(response)


class Calendar(View):
    """ A view to display bookings in a calendar """

    template_name = 'booking/calendar.html'

    def get(self, request, child_id, *args, **kwargs):
        if request.user.is_authenticated:
            try:
                family = Family.objects.get(user=request.user.id)

            except Family.DoesNotExist:
                return redirect('registration:regfamily')

            try:
                child = Child.objects.get(id=child_id)

            except Child.DoesNotExist:
                raise Http404()

            if child.family != family:
                raise Http404()

            periods = Period.objects.filter(end_date__gte=date.today())

            calendars = {}
            for period in periods:
                wednesday = []
                if period.name == 'Périscolaire':
                    all = Period.objects.all().exclude(name=period.name)
                    for obj in all:
                        wednesday += obj.get_days(2)

                calendars[period.name] = period.make_calendar(child, wednesday)

            context = {
                'child': child,
                'calendars': calendars
            }

            return render(request, self.template_name, context)

        else:
            return redirect('registration:login')

booking/templates/booking/calendar.html
{% extends 'home/base.html' %}
{% load static %}
  {% block content %}
    <section>
      <img class="banner-img" src="{% static 'booking/img/banner_2.jpg' %}" alt="">
      <div class="s-icon">
        <i class="far fa-calendar-alt fa-2x"></i>
      </div>
      <h1 class="section-title">RESERVATION</h1>
      <h2>{{ child.firstname }}</h2>
      <hr class="separator">
      <div class="instruction box-1">
        <p>Choississez une période dans la liste ci-dessous, puis marquez les jours à réserver</p>
        <p>à l'aide des marqueurs disponibles dans l'onglet de gauche.</p>
        <p class="text-small">Sélectionnez "Annuler" pour annuler une réservation</p>
      </div>
      <div class="options-box">
        <div class="option">
          <h4>Marqueurs</h4>
          <table>
            <tr>
              <td><input id="full-day" type="radio" name="day-option" value="full-day"></td>
              <td><label for="full-day">Journée</label></td>
              <td class="day full-day"> </td>
            </tr>
            <tr>
              <td><input id="half-day" type="radio" name="day-option" value="half-day"></td>
              <td><label for="half-day">Demi-journée</label></td>
              <td class="day half-day"> </td>
            </tr>
            <tr>
              <td><input id="cancel" type="radio" name="day-option" value="cancel"></td>
              <td><label for="cancel">Annuler</label></td>
              <td class="day"><i class="fas fa-times fa-2x" style="color: red"></i></td>
            </tr>
          </table>
        </div>
        <div class="arrow">
          <i class="fas fa-chevron-right fa-2x"></i>
        </div>
      </div>
      {% for calendar, months in calendars.items %}
      <div class="calendar">
        <h2>{{ calendar }}</h2>
        <div class="months">
        {% for month, weekdays in months.items %}
          <div class="month">
            <h3>{{ month }}</h3>
            <div class="weekdays">
            {% for weekday, days in weekdays.items %}
              <div class="weekday">
                <h4>{{ weekday }}</h4>
                {% for day, booking in days.items %}
                <div class="day-box">
                  {% csrf_token %}
                  {% if booking %}
                    {% if booking == 'full' %}
                    <button class="day" value="{{ day|date:'c' }}" disabled>{{ day|date:'j' }}</button>
                    {% elif booking.validated %}
                    <button class="day" value="{{ day|date:'c' }}" disabled>{{ day|date:'j' }}</button>
                    {% elif booking.whole == True %}
                    <button class="day full-day" value="{{ day|date:'c' }}">{{ day|date:'j' }}</button>
                    {% elif booking.whole == False %}
                    <button class="day half-day" value="{{ day|date:'c' }}">{{ day|date:'j' }}</button>
                    {% endif %}
                  {% else %}
                  <button class="day" value="{{ day|date:'c' }}">{{ day|date:'j' }}</button>
                  {% endif %}
                </div>
                {% endfor %}
              </div>
            {% endfor %}
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
      {% endfor %}
    </section>
    <script type="text/javascript">
      var childId = {{ child.id }}
    </script>
    <script type="text/javascript" src="{% static 'booking/js/scripts.js' %}"></script>
  {% endblock %}

booking/templates/booking/select_child.html
{% extends 'home/base.html' %}
{% load static %}
  {% block content %}
    <section>
      <img class="banner-img" src="{% static 'booking/img/banner_2.jpg' %}" alt="">
      <div class="s-icon">
        <i class="far fa-calendar-alt fa-2x"></i>
      </div>
      <h1 class="section-title">RESERVATION</h1>
      <hr class="separator">
      <div class="box-row-wrap">
        <div class="box-1 bg-lightblue rounded-borders">
          <h4>Sélectionner un enfant dans la liste ci-dessous:</h4>
        <ul class="not-dotted">
          {% for child in children %}
          <li><a class="form-button block" href="{% url 'booking:calendar' child_id=child.id %}">{{ child.firstname }}</a></li>
          {% endfor %}
        </ul>
        </div>
        <div class="box-1 bg-lightgrey rounded-borders">
          <h4>Vous souhaitez inscrire un autre enfant?</h4>
          <a class="form-button block" href="{% url 'registration:regchild_step1' %}">Ajouter un enfant</a>
        </div>
      </div>
    </section>
  {% endblock %}